### ISSUE TITLE
Support WKT representations that aren't mentioned by any of the crappy specs

### ISSUE THREAD

**Issue by tmcw** [mapbox/wellknown#14]
Apparently via https://github.com/Esri/terraformer-wkt-parser/blob/master/spec/wktSpec.js  WKT can have all kinds of things like EMPTY that I don't know about because there isn't a spec that I can read because the OGC is whiffing it so hard.

I'll implement fixes for things in the spec as soon as a spec is published in a web-accessible format. Until then, patches accepted. Call your OGC congressman, ask for HTML and to cut the jargon.

**Comment by sckott** [comment]
What is your feeling on supporting other objects like `CircularString` that aren't in this library, but mentioned on the Wikipedia page http://en.wikipedia.org/wiki/Well-known_text and in the OGC pdf http://www.opengeospatial.org/standards/sfa in the WKB section - Are you sticking to objects that have equivalents in GeoJSON?

**Comment by tmcw** [comment]
I'm happy to accept PRs implementing any additional types for this repo. For things without equivalents in GeoJSON, it would probably convert into non-curved shapes.

**Comment by sckott** [comment]
Okay. How often do you see other objects like `CircularString`, `CurvedPolygon`, etc. Are they essentially not used, or used enough to be worth implementing here and in clients for other langs

**Comment by tmcw** [comment]
Not very often, for me - though they may be more popular in other industries or areas - curve support in OSS at least is very limited, so maybe it's an Esri thing.

**Comment by tmcw** [comment]
Closing as idle. PRs are accepted that would completed this task but it is not one of my own priorities to implement it myself.
