### ISSUE TITLE
Parser accepts invalid points

### ISSUE THREAD

**Issue by perliedman** [mapbox/wellknown#20]
Not sure if it's in the scope of this lib, but it currently accepts invalid point entries, which in turn makes it spit out invalid GeoJSON.

Sample input:

```
POLYGON(1,2,3)
```

results in:

```json
{"type":"Polygon","coordinates":[[[1],[2],[3]]]}
```

From the PDF that shall not be mentioned, it appears that the grammar says a point must have at least x and y, possibly also z.

**Comment by tmcw** [comment]
Fixed in #24
