### ISSUE TITLE
brfs transform in package.json causing browserify error

### ISSUE THREAD

**Issue by chadwilcomb** [mapbox/wellknown#21]
Caveat: I am in the process of learning and setting up my first app using npm, grunt, browserify so this could be a noob issue:

Upon installing the wellknown module from npm, and requiring into my browserify project, I get an error when running Grunt that grunt-browserify cannot find the brfs module. Since your package.json specifies the brfs transform in the browserify options, I beleive either brfs should be in dependencies (rather than devDependencies) section of your package.json, or the browserify settings/transform should be removed. As a workaround, I simply installed brfs to my project and I no longer get the error.

**Comment by tmcw** [comment]
Fixed in cd08ac1e9e011f99d32a265f81dd9c5911e92595

**Comment by chadwilcomb** [comment]
:+1:
